version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: velvetaccardia/nestjs-app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    